### ISSUE TITLE
Fixed and short 密文固定

### ISSUE THREAD

**Issue by gary02** [sheepzh/make-zero#1]
比如 "abc",  "cba" 用我现在的password加密后分别是z01BA@, z01@AB,     这个时候”a“ 固定加密成B， 其他字符也是这样。

这样的话密文足够多的时候可以通过统计信息反推原文了吧？

**Comment by sheepzh** [comment]
是的，所以后面加了随机密文，用 currentTimestamp 和 toInt(password) 生成种子，放在密文的第一个字符用于解密，类似于文件校验头，密码长度越长随机性越大。源码在这[src/components/zero/cryptor/cryptor2.ts](https://github1s.com/sheepzh/make-zero/blob/main/src/components/zero/cryptor/cryptor2.ts)

**Comment by sheepzh** [comment]
> 比如 "abc", "cba" 用我现在的password加密后分别是z01BA@, z01@AB, 这个时候”a“ 固定加密成B， 其他字符也是这样。
> 
> 这样的话密文足够多的时候可以通过统计信息反推原文了吧？

是的，所以后面加了随机密文，用 currentTimestamp 和 toInt(password) 生成种子，放在密文的第一个字符用于解密，类似于文件校验头，密码长度越长随机性越大。源码在这 [src/components/zero/cryptor/cryptor2.ts](https://github1s.com/sheepzh/make-zero/blob/main/src/components/zero/cryptor/cryptor2.ts)
