### ISSUE TITLE
Firefox下部分功能无法正常使用

### ISSUE THREAD

**Issue by VEQeR0uXVqWVZodU** [sheepzh/make-zero#10]
- [x] textarea元素内无法使用选中加密，加密结果为z01(密文风格1)，input内可以
- [x] 不能读取剪贴板内容，加密或解密都不行
- [x] 扩展图标菜单内 使用指南 转到了static/static/guide.html而非static/guide.html
经测试 chrome103.0.5060.114(x64) 以上功能可正常使用
firefox版本102.0.1(x64)

**Comment by sheepzh** [comment]
谢谢反馈，bug 们我已复现。修复完成会通知您

**Comment by sheepzh** [comment]
Firefox 下无法读取 textarea 内的内容，为 getSelection 在 Firefox 下的 bug
> https://bugzilla.mozilla.org/show_bug.cgi?id=85686

**Comment by sheepzh** [comment]
已经在 v1.7.1 中修复
